/**
 * Created by yjy on 2017/3/31.
 */
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const FETCH_POSTS_CLEAR = 'FETCH_POSTS_CLEAR';

export const FETCH_POSTS_REQUEST_ALL = 'FETCH_POSTS_REQUEST_ALL';
export const FETCH_POSTS_FAILURE_ALL = 'FETCH_POSTS_FAILURE_ALL';
export const FETCH_POSTS_SUCCESS_ALL = 'FETCH_POSTS_SUCCESS_ALL';